;******************************************************************************
;*                               O P E N  T S
;******************************************************************************
;* SPDX-License-Identifier: GPL-3.0-or-later
;* Copyright 2026 OpenTS contributors
;*
;* See LICENSE.md for applicable additional terms and warranty disclaimers.
;******************************************************************************


;**************************************************************************
;**
;** FTOL.ASM - Floating point to integer conversion.
;**
;**************************************************************************

.586					; Target processor. Use instructions for Pentium class machines.
.model flat, C			; Use the flat memory model. Use C (cdecl) calling convention.


PUBLIC set_control_word
PUBLIC _ftol

extern FPU_FLAG:dword

OPTION LANGUAGE:C


; CODE --------------------------------------------------------------------

.CODE					; Indicates the start of a code segment.


;==========================================================================
;
; sub_6B2310 - xyz
;
; xyz
;==========================================================================

sub_6B2310		PROC

	mov eax, [esp+0]
	ret

sub_6B2310		ENDP


;==========================================================================
;
; set_control_word - xyz
;
; xyz
;==========================================================================
if 0
set_control_word	PROC

    local dble:qword
    local cw:dword

	fwait						; synchronize

	fstcw WORD PTR [cw]			; get control word
	fwait						; synchronize

	mov ax, WORD PTR [cw]		; round mode saved
	and eax, 0FFFFh				; set mode
	mov DWORD PTR FPU_FLAG, eax	; back to memory

	ret

set_control_word	ENDP
endif

set_control_word	PROC

	push ebp
	mov ebp, esp
	sub esp, 0Ch
	fwait						; synchronize

	fstcw WORD PTR [ebp-2]			; get control word
	fwait						; synchronize

	mov ax, WORD PTR [ebp-2]		; round mode saved
	and eax, 0FFFFh				; set mode
	mov DWORD PTR FPU_FLAG, eax	; back to memory
	leave
	ret

set_control_word	ENDP


;==========================================================================
;
; ftol - Convert floating point to integer.
;
; Calls to __ftol are generated by the compiler for code
; that needs to convert a floating point type to an integral type.
;
; @param	The floating point to convert to integer.
; @return	The integer converted from the floating point in EAX.
;
; Replacement for Visual C++ ftol.
;==========================================================================
if 0
_ftol PROC

    local dble:qword
    local cw:word

	;sub esp, 0Ch

	fnstcw WORD PTR [cw]		; save the control word

	lea eax, [dble]

	mov edx, DWORD PTR [cw]		; compare current control word
	and edx, 0FFFFh
	cmp edx, DWORD PTR FPU_FLAG
	jnz restore_cw

	fistp QWORD PTR [eax]		; store chopped integer

	mov edx, DWORD PTR [eax+4]	; return LS 32 bits
	mov eax, DWORD PTR [eax]	;        MS 32 bits
	;add esp, 0Ch

	ret

restore_cw:
	mov edx, DWORD PTR [FPU_FLAG]	; restore the control word
	mov DWORD PTR [cw], edx
	fldcw WORD PTR [cw]

	fistp QWORD PTR [eax]		; store chopped integer

	mov edx, DWORD PTR [eax+4]	; return LS 32 bits
	mov eax, DWORD PTR [eax]	;        MS 32 bits
	;add esp, 0Ch

	ret

_ftol	ENDP
endif

_ftol PROC

	sub esp, 0Ch

	fnstcw WORD PTR [esp]		; save the control word

	lea eax, [esp + 4]

	mov edx, DWORD PTR [esp]		; compare current control word
	and edx, 0FFFFh
	cmp edx, DWORD PTR FPU_FLAG
	jnz restore_cw

	fistp QWORD PTR [eax]		; store chopped integer

	mov edx, DWORD PTR [eax+4]	; return LS 32 bits
	mov eax, DWORD PTR [eax]	;        MS 32 bits
	add esp, 0Ch

	ret

restore_cw:
	mov edx, DWORD PTR [FPU_FLAG]	; restore the control word
	mov DWORD PTR [esp], edx
	fldcw WORD PTR [esp]

	fistp QWORD PTR [eax]		; store chopped integer

	mov edx, DWORD PTR [eax+4]	; return LS 32 bits
	mov eax, DWORD PTR [eax]	;        MS 32 bits
	add esp, 0Ch

	ret

_ftol	ENDP

END ; END directive required at end of file.
