# Writes the build identity header that the debug log's startup banner reports.
#
# Run both at configure time and once per build, so the recorded commit follows HEAD without
# a reconfigure. The header is only rewritten when its contents change, so an ordinary rebuild
# does not force the logger to recompile.
#
# Expects OPENTS_VERSION, OPENTS_SOURCE_DIR, and OPENTS_STAMP_HEADER to be set.

set(OPENTS_COMMIT "unknown")
set(OPENTS_BRANCH "unknown")
set(OPENTS_COMMIT_DATE "unknown")
set(OPENTS_COMMIT_DIRTY 0)

find_package(Git QUIET)

# A build from a source archive has no repository, and git need not be installed at all.
# Neither is an error; the banner simply reports what it does not know.
if(GIT_FOUND AND EXISTS "${OPENTS_SOURCE_DIR}/.git")

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_COMMIT_RESULT
    )
    if(GIT_COMMIT_RESULT EQUAL 0 AND GIT_COMMIT)
        set(OPENTS_COMMIT "${GIT_COMMIT}")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --abbrev-ref HEAD
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_BRANCH
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_BRANCH_RESULT
    )
    if(GIT_BRANCH_RESULT EQUAL 0 AND GIT_BRANCH)
        set(OPENTS_BRANCH "${GIT_BRANCH}")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" log -1 "--format=%cd" "--date=format:%Y-%m-%d %H:%M:%S"
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_DATE
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_DATE_RESULT
    )
    if(GIT_DATE_RESULT EQUAL 0 AND GIT_DATE)
        set(OPENTS_COMMIT_DATE "${GIT_DATE}")
    endif()

    # Untracked files are excluded deliberately: a scratch file beside the sources does not
    # make the built code differ from the commit.
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" status --porcelain --untracked-files=no
        WORKING_DIRECTORY "${OPENTS_SOURCE_DIR}"
        OUTPUT_VARIABLE GIT_STATUS
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE GIT_STATUS_RESULT
    )
    if(GIT_STATUS_RESULT EQUAL 0 AND NOT GIT_STATUS STREQUAL "")
        set(OPENTS_COMMIT_DIRTY 1)
    endif()

endif()

set(STAMP_CONTENT
"/*******************************************************************************
 *                                O P E N  T S
 *******************************************************************************
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright 2026 OpenTS contributors
 *
 * See LICENSE.md for applicable additional terms and warranty disclaimers.
 ******************************************************************************/

/* Generated by cmake/GitStamp.cmake. Edits are overwritten by the next build. */

#pragma once

#define OPENTS_VERSION       \"${OPENTS_VERSION}\"
#define OPENTS_COMMIT        \"${OPENTS_COMMIT}\"
#define OPENTS_BRANCH        \"${OPENTS_BRANCH}\"
#define OPENTS_COMMIT_DATE   \"${OPENTS_COMMIT_DATE}\"
#define OPENTS_COMMIT_DIRTY  ${OPENTS_COMMIT_DIRTY}
")

# Rewriting an identical header would make every build recompile the logger.
set(STAMP_EXISTING "")
if(EXISTS "${OPENTS_STAMP_HEADER}")
    file(READ "${OPENTS_STAMP_HEADER}" STAMP_EXISTING)
endif()

if(NOT STAMP_EXISTING STREQUAL STAMP_CONTENT)
    file(WRITE "${OPENTS_STAMP_HEADER}" "${STAMP_CONTENT}")
    message(STATUS "OpenTS: build stamp ${OPENTS_COMMIT} on ${OPENTS_BRANCH}")
endif()
